Dealing with categorical and integer-valued variables in Bayesian Optimization with Gaussian processes
SMTorg/smt pull request #220
Opened 2020-07-23 15:51 UTC by Paul-Saves

Hello,
This is the mixed ego optimization with mixed models.

How to use?
By default, the type of the variables is assumed continuous.
If not, you can pass a mixed surrogate s.

s = KRG( vartype=["cont","int",("cate",3),("cate",2)])

ego = EGO(n_doe=n_doe,n_iter=n_iter, criterion=criterion,xlimits=xlimits,qEI=qEI,tunnel=0,vartype=vartype, surrogate=s )

I have written here the pseudo-code:
![image](https://user-images.githubusercontent.com/56302141/88308043-e09e6500-cd0c-11ea-910b-0b5ce6f8e40a.png)
Reference: [GMHL.pdf](https://github.com/SMTorg/smt/files/4967282/GMHL.pdf)

2020-09-02 09:50 UTC, Paul-Saves commented
Add assign_labels to outputs of ego: x_data

2020-09-08 13:59 UTC, Paul-Saves commented
h

2020-09-09 08:29 UTC, relf requested changes

2020-09-09 08:29 UTC, relf commented on doc/_src_docs/applications/ego.rstx
> +You can penalize already evaluated point in EI via tunneling (not recommanded for high dimensional problems).
Maybe add a sentence or two to explain the tunneling principle a bit more... (why I would do that? what is it?)

2020-09-09 08:29 UTC, relf commented on smt/applications/ego.py
> +        declare("tunnel", 0, types=int, desc="1 to enable tunneling in ei")
tunnel should be better implemented by a boolean (see verbose above) and maybe renamed enable_tunneling with further explanations in the description (enable the penalization of points that have been already evaluated in EI criterion).

2020-09-09 08:29 UTC, relf commented on smt/applications/ego.py
> +        declare("surrogate", KRG(print_global=False), desc="surrogate model to use")
I think you can declare types=KrgBased or more strictly types=(KRG, KPLS, KPLSK) maybe description could be more specific "SMT kriging-based surrogate model used internally"

2020-09-09 08:29 UTC, relf commented on smt/applications/tests/test_ego.py
> +        print("evaluator")
print information given by the test runner, could be removed

2020-09-09 08:29 UTC, relf commented on smt/applications/tests/test_ego.py
> +    Test class
Well... less informative than the name of the class above, could be removed

2020-09-09 08:29 UTC, relf commented on smt/applications/ego.py
> +                fun, self.gpr._assign_labels(x_doe, self.options["xlimits"])
_assign_labels should be renamed assign_labels. The underscore in front of a method name specify a protected method normally not used outside of the class or subclasses. same thing for project_values

2020-09-09 15:50 UTC, relf approved these changes
Thanks for this new feature in SMT!

2020-09-09 15:51 UTC, merged

2020-09-09 15:57 UTC, Paul-Saves commented
Thanks a lot for your help !