Mixed surrogate model
SMTorg/smt pull request #237
Opened 2020-10-14 13:14 UTC by raul-rufato

I am a student at ISAE-Supaero and I do research with Professor Morlier. I am implementing the Gower distance for kernel calculation of mixed variables (only available for KRG). I don't know how I should go about creating the documentation for this pull request, as I just added it as an extra case inside MixedIntegerSurrogate. I added a notebook in the home folder that performs an example using the Gower distance.

Thank you. 

Regards,

Raul

2020-10-15 13:16 UTC, relf requested changes
Binary files utils/neural_net/__pycache__/... should not be included in the PR.
You should add some tests in tests/test_krg.py to check proper results of your code
We also use the code formatter named black, you should use it on the file you modify.
Finally your code seems to break some other tests in SMT, so you have to ensure that the SMT test suite pass at least in your environment.

2020-10-15 13:16 UTC, relf commented on smt/surrogate_models/krg_based.py
> +                    if not isinstance(Xt, np.ndarray): Xt = np.asarray(Xt)
already tested above?

2020-10-15 13:16 UTC, relf commented on smt/surrogate_models/krg_based.py
> +            if not isinstance(Xt, np.ndarray):
same code as in initialize? Is it useful? If yes should be in a separate function

2020-10-15 13:16 UTC, relf commented on smt/surrogate_models/krg_based.py
> +        if self.options["corr"] != "gower_corr":
better to test for equality

2020-10-19 14:07 UTC, Paul-Saves commented
You should merge from SMTorg/SMT master branch. My branch is not up to date anymore. 
Moreover, mixed integer were implemented in the master. 
So, when you merge, you should pull master branch.

2020-11-17 13:42 UTC, closed without merging