INT type in mixed integer models is now about ordered variables
SMTorg/smt pull request #326
Opened 2021-07-30 11:48 UTC by Paul-Saves

Hello,
If I have an integer variable, that is quantitative, like X ∈ { 1,2,3}, it works but for a variable that is of the form X ∈ { 1,2,4} or X ∈ { 1,2.5,3}, there is no solution yet.

This enhancement replace INT type for integer variables into a more general ORD type for ordinal values.

2021-07-30 13:04 UTC, Paul-Saves commented
fix #313

2021-08-16 09:50 UTC, relf requested changes
We should add a new type (like `ORD`) to represent the new ordered variable capability (and keep INT for integer variables), as it is a bit misleading to have INT type for {"0", "3.5"} values.

2021-08-16 09:50 UTC, relf commented on smt/applications/mixed_integer.py
> +            if xtyp == "int_type" and isinstance(xlimits[i][0], str):
`if xtyp == INT and`...

2021-08-16 09:50 UTC, relf commented on smt/applications/mixed_integer.py
> +                if np.array_equal(sortedlistint, listint) == False:
`if not np.array_equal(sortedlistint, listint):` ...

2021-08-16 09:50 UTC, relf commented on smt/applications/tests/test_mixed_integer.py
> +    def test_unfold_xlimits_with_continuous_limits2(self):
Better to suffix the test name with some information about the specificity of the test, like `test_unfold_xlimits_with_continuous_limits_and_ordinal_values`

2021-08-17 08:34 UTC, Paul-Saves commented
Can't we just keep ORD and deprecate old INT type as ORD generalize INT ?

2021-08-17 09:24 UTC, relf commented
> 
> 
> Can't we just keep ORD and deprecate old INT type as ORD generalize INT ?

Yes sure! Deprecation means it is still working in at least in a next minor release (SMT 1.1) and ideally is removed in next major release (well I do not think we aim at a SMT 2.0 just for that).

2021-08-17 09:53 UTC, relf commented
Well, even if ORD can supersede INT, would not it be interesting to keep INT anyway (no deprecation then) to have clearer/cleaner specification ([1, 2, 3] vs ["1", "2", "3"]) when we have integer variable?

2021-08-17 12:02 UTC, Paul-Saves commented
I think INT should be removed. It makes no sense to have both INT and ORD as the variables are treated similarly.

2021-08-17 13:57 UTC, relf commented
Ok then could you just keep a test with INT to ensure it still works (we will remove all this later on after SMT 1.1).

2021-08-17 14:00 UTC, relf commented
> I think INT should be removed later. It makes no sense to have both INT and ORD as the variables are treated similarly.

It was just a matter of user-facing API, but ok it is not worth the code complexity.

2021-08-18 08:37 UTC, relf commented
Looks good to me, anything to add?

2021-08-18 08:45 UTC, Paul-Saves commented
> 
> 
> Looks good to me, anything to add?

I don't think so, it's ok for me

2021-08-18 09:11 UTC, merged