Mi matrix
SMTorg/smt pull request #330
Opened 2021-08-30 08:48 UTC by Paul-Saves

2021-09-15 09:02 UTC, Paul-Saves commented
@relf Is it ok for you ? I will develop new mixed integer kernels from this code

2021-09-15 14:00 UTC, relf requested changes
Maybe you should add at least one new kernel just to test the changes because at the moment the complexity you introduce does not bring any value and part of the code is simply not tested as categorical_kernel is always None.

2021-09-15 17:18 UTC, Paul-Saves commented on smt/applications/tests/test_ego.py
> +        xtypes = [(ENUM, 3), (ENUM, 2), ORD, FLOAT]
For these kernel, we need to put the ENUM at the beggining, otherwise, theta are badly estimated but I did not manage to understand why :(

2021-09-20 09:46 UTC, Paul-Saves commented on smt/applications/tests/test_ego.py
> +        xtypes = [(ENUM, 3), (ENUM, 2), ORD, FLOAT]
krg_utils, l.275
    D = np.concatenate((D_cat, D_num), axis=1)

2021-09-20 12:12 UTC, Paul-Saves commented on smt/applications/tests/test_ego.py
> +        xtypes = [(ENUM, 3), (ENUM, 2), ORD, FLOAT]
Ok, now, this bug is solved on my clone of the repo

2021-09-22 08:45 UTC, Paul-Saves commented
I just wanna run thee coverall that crashed lately

2021-09-28 09:36 UTC, closed without merging