Fix QP and clean QP and LS
SMTorg/smt pull request #396
Opened 2023-01-11 19:42 UTC by Paul-Saves

Add data normalization in QP

2023-01-11 20:56 UTC, Paul-Saves commented
Thanks to @relf, following issues of #394

2023-01-12 09:43 UTC, relf requested changes

2023-01-12 09:43 UTC, relf commented on smt/applications/mixed_integer.py
> +            self._surrogate.options["xlimits"] = self._xlimits
I am still puzzled by this `xlimits` option. Why not use the values themselves to normalize when using Gower distance? Like `standardization`?

2023-01-12 09:43 UTC, relf commented on smt/surrogate_models/qp.py
> +from smt.utils.kriging_utils import standardization
Well, `standardization` should be moved in a another module in utils? `utils/misc.py` ?

2023-01-12 09:43 UTC, relf commented on smt/surrogate_models/qp.py
> +        x = (x -self.X_offset)/self.X_scale
Seems you need to pass `black`.

2023-01-12 12:54 UTC, Paul-Saves commented
Ok, j'ai passé `black`.  Le reste sera traité dans la prochaine PR

2023-01-12 14:14 UTC, merged