Change API
SMTorg/smt pull request #398
Opened 2023-01-15 16:40 UTC by Paul-Saves

- Remove redundant file
- Move standardization as asked in #396 
- Add the variable xspec = {xlimits, xtypes} in every KRG based model. 
- Until now, only GEKPLS and RMTS-based models used xlimits. Now, it is more consistent.
- Mixed integer only supports KRG based models now.
- The random seeds are back in EGO thanks to #397.
- Update tests and rework RMTS tests.

2023-01-16 10:48 UTC, relf requested changes
Thanks Paul!

2023-01-16 10:48 UTC, relf commented on smt/surrogate_models/krg_based.py
> +            desc="""xspecs : x specifications (xtypes,xlimits)
`{"xtypes": array-like, "xlimits":  array-like}` instead of `(xtypes, xlimits)`

2023-01-16 10:48 UTC, relf commented on smt/utils/misc.py
> +    X_scale[X_scale == 0.0] = 1.0
Should be better to test < 1e-15 or 100.*sys.float_info.epsilon instead of == 0.

2023-01-16 10:48 UTC, relf commented on smt/utils/test/test_kriging_utils.py
> -    def test_standardization(self):
We should have some tests for standardization

2023-01-16 10:48 UTC, relf commented on smt/utils/misc.py
> +    variable by its standard deviation. If scale_X_to_unit, we scale the input
`scale_X_to_unit` option does not exist anymore.

2023-01-17 23:06 UTC, Paul-Saves commented
- Add XSpec class in krg_utils
- Add MixedIntegerKriging in EGO

2023-01-17 23:38 UTC, Paul-Saves commented
It's okay for me ! :) 🎉

2023-01-18 09:23 UTC, relf reviewed
Thanks Paul! I will merge the PR but I am going to rework the `XSpec` class, It will be simpler if I show you what I have in mind when we discussed about it.

2023-01-18 09:33 UTC, Paul-Saves commented
Perfect, let's keep in touch !

2023-01-18 10:45 UTC, merged