Update doc for SMT 2.0
SMTorg/smt pull request #412
Opened 2023-03-01 19:25 UTC by Paul-Saves

Update doc for SMT 2.0

2023-03-01 19:29 UTC, Paul-Saves commented
Take #410 into consideration and rebuild the doc. @relf

2023-03-02 10:10 UTC, relf requested changes

2023-03-02 10:10 UTC, relf commented on doc/_src_docs/applications/Mixed_Hier_usage.rstx
> +  .. autoclass:: smt.utils.kriging.XSpecs
See generated doc. role is missing in description  and xroles parameter is not rendered properly.

2023-03-02 12:02 UTC, Paul-Saves commented on doc/_src_docs/applications/Mixed_Hier_usage.rstx
> +However, the functioning of ``ORD`` is twofold. As previously mentioned, it can be used like [lower bound, upper bound], in this case [0,5] will corresponds to [0,1,2,3,4,5]. But, on the other hand,
I do not remember... I'll go for no float allowed, for now

2023-03-02 14:00 UTC, relf approved these changes

2023-03-02 14:00 UTC, merged