Implements the Arc-kernel for hierarchical variables
SMTorg/smt pull request #417
Opened 2023-03-24 15:44 UTC by Paul-Saves

Implement Hierarchical kernels with 2 options (ALG and ARC kernels)
`              

             declare(
            "hierarchical_kernel",
            MixHrcKernelType.ALG_KERNEL,
            values=[
                MixHrcKernelType.ALG_KERNEL,
                MixHrcKernelType.ARC_KERNEL,
            ],
            desc="The kernel to use for mixed hierarchical inputs. Only for non continuous Kriging",
        )

`

2023-03-27 07:28 UTC, relf requested changes

2023-03-27 07:28 UTC, relf commented on smt/utils/kriging.py
> +        maxmetanum,
rename `max_meta_num` to have consistent naming

2023-03-27 18:22 UTC, merged

2023-03-27 18:27 UTC, relf commented
I merged but I've noticed there is no test for the new `ArcKernel` variant.

2023-03-28 11:51 UTC, Paul-Saves commented
> I merged but I've noticed there is no test for the new `ArcKernel` variant.

Fixed in #421. I put ` Arc-Kernel`   in the Goldstein test and ` Arg-Kerne` l in the Goldstein illustration for the documentation.