Added 4 tests for noisy GPs and for GPX
SMTorg/smt pull request #586
Opened 2024-06-14 13:01 UTC by MaelTremouille

Added 4 tests to complete the tests in the test_ego.py file and added design_space features in GPX

2024-06-14 13:26 UTC, relf requested changes
Thanks for your contribution! You should install the VScode extension Ruff and configure to automatically format the code when you save files, otherwise use `ruff format <file>`.

2024-06-14 13:26 UTC, relf commented on smt/applications/ego.py
> +        # New declaration for noise0
Remove useless comment (changes are visible in the PR).

2024-06-14 13:26 UTC, relf commented on smt/applications/ego.py
> +            "noise0",
I do not see any usage of options["noise0"]. We do not need to declare a `noise0` option in EGO, it is already an option of `KRG`. To be removed.

2024-06-14 13:26 UTC, relf commented on smt/applications/tests/test_ego.py
> +            surrogate=KRG(design_space=design_space, print_global=False),
`noise0` should be passed in KRG call

2024-06-14 13:26 UTC, relf commented on smt/applications/tests/test_ego.py
> +    def test_function_ego_GPN_1D(self):
maybe use `noisy_KRG` instead of `GPN`

2024-06-17 09:38 UTC, MaelTremouille commented
Review of the comments from the last PR and corrections

2024-06-17 13:40 UTC, MaelTremouille commented
I formated my files with Ruff

2024-06-17 14:43 UTC, relf requested changes
You have to create another branch restarting from master containing the changes related to the feature 'no theta optimization'. Moreover, instead of adding a new option maybe we can use the `hyper_opt` option and add a `NoOptim` value or even better `None` to state that `theta0` is used as is.

2024-06-18 08:20 UTC, closed without merging