Smt connection with SMTOrg/designspace
SMTorg/smt pull request #651
Opened 2024-09-17 20:20 UTC by Paul-Saves

Create the connection between SMT and SMT-Design-Space. 
Remove code related to SMT-Design-Space moved in a new repo 

--- SMTOrg/SMT-Design-Space
- Add the class ArchDesignSpaceGraph(DesignSpace) to DesignSpace.py
- Improve seeding in DesignSpace.py
- Fix a bug when rounding and the lower bound is not zero
----
- Improve tests & notebook accordingly

2024-09-30 16:52 UTC, Paul-Saves commented
@relf Okay for me!

2024-10-01 08:33 UTC, Paul-Saves commented
I fixed the initialization for Collab.

2024-10-01 08:41 UTC, relf requested changes
Actually the module name `smt_design_space` is confusing, I suggest to rename it in `smt_design_space_ext` for external or extension I mean smt has an API for design space and a standalone internal basic design space handling which can be enhanced using `smt_design_space_ext` module.
Sorry for this late suggestion. [Naming is a well-know hard problem in computer science]( https://martinfowler.com/bliki/TwoHardThings.html)

2024-10-01 08:41 UTC, relf commented on smt/design_space/__init__.py
> +    HAS_SMTDesignSpace = True
constant are all uppercase ie HAS_SMT_DESIGN_SPACE. I would prefer HAS_SMT_DESIGN_SPACE_EXT or HAS_DESIGN_SPACE_EXT for a shorter name.

2024-10-02 06:48 UTC, relf commented on smt/design_space/tests/test_design_space.py
> +if os.getenv("FORCE_RUN_PLAIN_BASICS"):
Would not it be the opposite? I mean when the variable is set we want to run the "else" statements? Maybe the variable should be renamed RUN_PLAIN_DESIGN_SPACE_TEST as it is only used for test purpose.

2024-10-02 10:08 UTC, relf approved these changes

2024-10-02 10:10 UTC, merged